name: Generate Mermaid Diagrams

on:
  push:
    paths:
      - "docs/flows/*.mmd"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      # ① ソースコード取得
      - name: Checkout repository
        uses: actions/checkout@v3

      # ② Node.js セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ③ Mermaid CLI インストール
      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      # ④ Mermaid ファイルを PNG / SVG に変換
      - name: Generate Diagrams
        run: |
          for f in docs/flows/*.mmd; do
            n=${f%.mmd}
            echo "Generating diagram for $f"
            npx mmdc -i "$f" -o "$n.png" --no-sandbox
            npx mmdc -i "$f" -o "$n.svg" --no-sandbox
          done

      # ⑤ 生成された画像をコミット
      - name: Commit Diagrams
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/flows/*.png docs/flows/*.svg || true
          git commit -m "Auto-generate Mermaid diagrams" || echo "No changes to commit"
          git push
