name: Generate Mermaid Diagrams

on:
  push:
    paths:
      - "docs/flows/*.mmd"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate Diagrams
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
        run: |
          for f in docs/flows/*.mmd; do
            n=${f%.mmd}
            echo "Generating diagram for $f"
            mmdc -i "$f" -o "$n.png"
            mmdc -i "$f" -o "$n.svg"
          done

      - name: Commit Diagrams
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/flows/*.png docs/flows/*.svg || true
          git commit -m "Auto-generate Mermaid diagrams" || echo "No changes to commit"
          git push
